[services]
user = [
    "docker.socket",
    "hypridle.service",
    "hyprpaper.service",
    "hyprpolkitagent.service",
    "hyprsunset.service",
    "mako.service",
    "waybar.service",
]
system = ["greetd"]
